version: "3.9"
services:
  app:
    build: .
    volumes:
      - .:/app
      - venv:/app/venv
    ports:
      - "5000:5000"
    container_name: video-api
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/vapi
      - SECRET_KEY=my-secret-key
      - FLASK_APP=run.py
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  venv:
  postgres_data: