version: "3.9"
services:
  app:
    build: .
    command: gunicorn --workers 4 --reload --bind 0.0.0.0:5000 "app.factory:create_app()"
    volumes:
      - .:/app
      - venv:/app/venv
    environment:
        - FLASK_ENV=development

  worker:
    build: .      
    command: celery -A app.celery_worker.celery worker --loglevel=INFO --concurrency=2      
    volumes:
      - .:/app
    container_name: video-api-worker
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/vapi
      - SECRET_KEY=my-secret-key
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=db+postgresql://postgres:postgres@db:5432/vapi
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db  
      
volumes:
  venv: